### ISSUE TITLE
frp穿透不好用了吗？

### ISSUE THREAD

**Issue by binglongl** [swordstudiox/freenat#1]
frp穿透不好用了吗？
http://freenat.bid:7500
我连这个地址都打不开了，是服务器出问题了吗？

**Comment by navyia** [comment]
你好，我遇到了同样的问题

**Comment by swordstudiox** [comment]
> frp穿透不好用了吗？
> http://freenat.bid:7500
> 我连这个地址都打不开了，是服务器出问题了吗？



> 你好，我遇到了同样的问题

已经好了，之前的服务器不稳定，已经切换，，，由于共享服务器维护艰难，很容易出现不可访问的情况，建议自建frp服务器
